services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    - DATABASE_URL=postgresql://user:password@db:5432/ulcontrol

  db:
    image: postgres:13  
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ulcontrol
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


